name: Run Tests

on:
  push:
    branches: [main, staging, dev]
  pull_request:
    branches: [main, staging, dev]

jobs:
  test:
    name: ğŸ”¬ Linting, ğŸ“Š PyTest
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install poetry, isort, black
        run: pipx install poetry isort black

      - name: View poetry, isort, black versions
        run: |
          poetry --version
          isort --version-number
          black --version

      - name: ğŸ Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: 3.12
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-root
      
      - name: ğŸ”¬ Python Lint (isort/black)
        run: |
          isort --check-only --quiet .
          black --check .

      - name: ğŸ“Š Run tests
        run: poetry run pytest -rpP
